### ISSUE TITLE
Formatting for different resolutions

### ISSUE THREAD

**Issue by MeganOhalloran** [Capping-CPCA/Web-App#104]
Everything on Referrals & Intake was nice and pretty on your screen, but because my laptop is a little smaller, things got a tiny bit messed up. Not a huge problem, but something that could probably change.
![capture1](https://user-images.githubusercontent.com/10644106/32582250-d1aa65aa-c4bb-11e7-8d14-f94f16b7a2d0.PNG)
![capture](https://user-images.githubusercontent.com/10644106/32582252-d35c38c4-c4bb-11e7-9afe-d77f4dfb16a5.PNG)

**Comment by algozine** [comment]
Really low priority for now ... all of the screens including the laptop screen at CPCA are huge .. BUT, perhaps ensuring it all looks good at the client location is a good idea.

**Comment by Scott123180** [comment]
Duplicate Issue. Issue is described in #171 and is a result of not implementing flex-box.
