### ISSUE TITLE
Placeholder Text for Questions and etc

### ISSUE THREAD

**Issue by KCoterwas** [Capping-CPCA/Web-App#105]
(I know this was discussed in class but just putting it here for record keeping)
Currently the placeholder text shows the questions, but disappear as soon as someone types into it. The questions should be outside of the text box so the participant can reference the question as they are answering it. This applies to several fields within the forms as well.

**Comment by christianmenk** [comment]
Chris and Greg went to Gwen and went over the forms with her and brought this question up and she said she likes having the full questions as the placeholders, and doesn't foresee a problem with forgetting what to write in. Thanks!
