### ISSUE TITLE
Placeholder consistency

### ISSUE THREAD

**Issue by KCoterwas** [Capping-CPCA/Web-App#107]
Blank text fields should either have nothing or something similar to "Write response here..." or "Type here..."

**Comment by algozine** [comment]
This is a really good practice, and should be brought up at the next class so that EVERYONE does this consistently... or, perhaps you could write an email out to all of the code leaders in #collaborators so they look for this on code review?

**Comment by christianmenk** [comment]
All placeholders are updated in our most recent pull request
