### ISSUE TITLE
Cut-off Headers

### ISSUE THREAD

**Issue by KCoterwas** [Capping-CPCA/Web-App#108]
In certain window sizes, long header names such as "Initial Contact Form- Self-Referral" gets cut off behind "PEP Manager."

**Comment by algozine** [comment]
Low priority.. but certainly something that should get fixed before final deployment

**Comment by michelleburd** [comment]
Has this been fixed? @sbohner14335 If not, it's a mobile problem which we have as parking lot. @algozine
