### ISSUE TITLE
Pop-up for removing 

### ISSUE THREAD

**Issue by MeganOhalloran** [Capping-CPCA/Web-App#109]
When removing child/party member, a pop-up appears; looks a little weird. 
![capture3](https://user-images.githubusercontent.com/10644106/32582942-4516771a-c4bf-11e7-884f-94b042fb9ac1.PNG)

**Comment by ghost** [comment]
What's weird on this `confirm()`? If it's `10.11.12.33 says:` then that's not changeable, but can be worked around with jQuery

**Comment by algozine** [comment]
I would prefer it not say an IP@ .. that's just not good UI in general.. however, I would suggest that fixing this is a low priority, and certainly not something to be fixed before we install tomorrow.

**Comment by vmjoseph** [comment]
As a suggestion, I'd recommend using a [bootstrap modal](https://getbootstrap.com/docs/4.0/components/modal/). This will more easily get rid of that pesky "IP says:" message, as well as match our current UI.

In terms of handling user input, you should be able to use button clicks as a detection.
Here's an example of what it would look like:
![removechildmodal](https://user-images.githubusercontent.com/9935166/32791076-1ee012fe-c92e-11e7-9e0b-92d39e9f188a.PNG)

or

![removechildmodaloutline2](https://user-images.githubusercontent.com/9935166/32791911-0fadd9fe-c930-11e7-84eb-367b2e1564b4.PNG)


Here's what you would need to do to implement the modal:
1. Insert the modal body in your form html page
```html
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Remove Child?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	  Are you sure you wish to remove this child? This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" id ="confirmid" class="btn cpca" data-dismiss="modal">OK</button>
        <button type="button" id ="cancleid" class="btn btn-secondary"  data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
```

2. In your ```clone-form-td.js``` file, around line 89, call the modal
```javascript
	$("#exampleModal").modal();
```
This is where you would handle the user input, so  you could say something like:
```javascript
$("#confirmid").click(function(){
     //do something here
});
```
and do the same for the cancel button.

If you have multiple modals, simply change the content of the modal on click. For example:
```javascript

$('#btnDelMember').click(function () {
     $("#exampleModalLabel").html("another modal title");
     $(".modal-body").html("Warning text goes here");
});
```
and then add your input handling there.
