### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Web-App#11]
Add a timeout to the PHP session after a certain amount of time (1 hour?).

**Comment by k6789j** [comment]
If we do this, make sure we save the state in some way if they are filling out a form

**Comment by algozine** [comment]
hmm.... we should ask the client ... also, I am thinking that their Windows environment may have a timeout that is mandated by their security policy, so us enforcing one on our app might not be necessary?
