### ISSUE TITLE
"Remove Member/Party"

### ISSUE THREAD

**Issue by KCoterwas** [Capping-CPCA/Web-App#110]
If there is only one member of the household or party, should the remove option be displayed? Also, isn't possible to have no household members? Is it possible to accommodate for those situations?

**Comment by christianmenk** [comment]
Currently, the remove option is greyed out, but I could set the visibility to hidden instead. Also, are you suggesting that upon entering the household panel there should only be a button to add a member that creates the first entry instead of displaying it initially?

**Comment by KCoterwas** [comment]
Yes, hidden would be ideal. What you're suggesting could work, but I'm not sure if people would be confused as to add household members. Maybe you could have a field asking how many people are in the household then generating that many forms for them to fill out?
