### ISSUE TITLE
Create a Way For SuperUsers to add languages to the DB

### ISSUE THREAD

**Issue by michelleburd** [Capping-CPCA/Web-App#135]
Perhaps a settings page or something along those lines that can be accessed from the User Management page?

**Comment by algozine** [comment]
This could be accomplished by documenting how I update the postgres instance on the client system using PGAdmin ... it does not have to be a coded UI screen option.

**Comment by michelleburd** [comment]
I will do that for now, and the UI option can be a small parking lot idea for later. It wouldn't be hard to do at all.

**Comment by michelleburd** [comment]
The documentation has been finished and sent to the appropriate people.
