### ISSUE TITLE
Monthly Reports slow to generate report

### ISSUE THREAD

**Issue by stickzman** [Capping-CPCA/Web-App#140]
Right now each number displayed in Monthly Reports is a separate query to the database.  This results in a long load time.

**Comment by blackjack26** [comment]
I would suggest that if possible, add something like a loading indicator if it might always take a little bit to load. This way the user at least sees something on the page.

**Comment by stickzman** [comment]
Loading indicator added and pushed to monthly-queries branch. Also decreased number of queries, seen in pull request.
