### ISSUE TITLE
Edit forms on View Participant page

### ISSUE THREAD

**Issue by sbohner14335** [Capping-CPCA/Web-App#165]
Since we are going to be implementing edit functionality for all of our forms, could you guys create view/edit buttons for each of the forms on the View Participant page?

**Comment by vmjoseph** [comment]
If you are referring to the ability to edit/view participant form data, that functionality would be best placed on it's own page. For example, when the user clicks the participant's "View Intake Packet" button, they will be redirected to another page with that particular participant's intake packet database view. This page would be the most appropriate for viewing/editing anything related to the intake packet.

**Comment by sbohner14335** [comment]
Yes that's exactly what I'm talking about, the buttons will link you to our forms that display all of the appropriate participant data to edit/update. Could we do a button for the referral and self-referral forms too like we have for intake?
