### ISSUE TITLE
Attendance, Age Validation >18

### ISSUE THREAD

**Issue by ghost** [Capping-CPCA/Web-App#166]
According to the PEP information available online and @algozine it's entirely possible for someone under 18 to be in classes.

https://github.com/Capping-CPCA/Web-App/blob/cbb61e3639aeca61be5e01bb22ed15e96bad4a91/public/js/attendance-scripts/attendance-form-add-new-person.js#L110

**Comment by Scott123180** [comment]
Thanks for raising the issue, do you know what is the cutoff age? Should we allow for 12 or higher?

**Comment by algozine** [comment]
Why do we need to have a cutoff age? Did the client request one? 

-Professor Algozzine


   Scott Hansen --- Re: [Capping-CPCA/Web-App] Attendance, Age Validation >18 (#166) --- 
    From:"Scott Hansen" <notifications@github.com>To:"Capping-CPCA/Web-App" <Web-App@noreply.github.com>Cc:"Chris Algozzine" <christopher.algozzine@marist.edu>, "Mention" <mention@noreply.github.com>Date:Fri, Nov 17, 2017 12:32 PMSubject:Re: [Capping-CPCA/Web-App] Attendance, Age Validation >18 (#166)
  
  Thanks for raising the issue, do you know what is the cutoff age? Should we allow for 12 or higher?

**Comment by ghost** [comment]
Any positive number is a safe bet. If they entered it wrong they could always update it.
