### ISSUE TITLE
Facilitator Status on View Page

### ISSUE THREAD

**Issue by dtoverington** [Capping-CPCA/Web-App#170]
I don't see a way in the User Management section to see if an employee is a facilitator without being in the edit page. Can there be a line that says their facilitator status when viewing an employee's info?

**Comment by michelleburd** [comment]
You would know if the employee was a facilitator if they had a language associated with them. I realize this is not very straightforward. I will add a line that says whether they are a facilitator or not. Thank you for the suggestion!
