### ISSUE TITLE
Referrals and Intake Formatting

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Web-App#171]
As a result the form items are squished to one side and do not align correctly.

_edit: turns out regular grid is okay, just optimizing this so that it works on 1024px screen width. This also ensures that the print functionality works correctly_

**Comment by sbohner14335** [comment]
That page you linked me is a 404

**Comment by ghost** [comment]
Not sure this issue has enough detail. Explain what's wrong with the formatting, and what changes need to be made.

**Comment by Scott123180** [comment]
Updated the description to include more detail of the issue and fixed the link issue.

**Comment by Scott123180** [comment]
I will have to manually merge the changes that took place in #190 

Changes are currently being made on https://github.com/Capping-CPCA/Web-App/tree/103-intake-referral-ui-fixes

**Comment by Scott123180** [comment]
changes are in place on 103-intake-referral-ui-fixes. Waiting for class feedback on Wednesday's class (12/6/17). See pull request #197

**Comment by christianmenk** [comment]
decision was made to keep original formatting as the user can use the zoom functionality to prevent scaling issues
