### ISSUE TITLE
Custom Reports pulling Curricula w/ DF

### ISSUE THREAD

**Issue by ghost** [Capping-CPCA/Web-App#175]
[Custom Reports](https://github.com/Capping-CPCA/Web-App/blob/develop/views/reports/custom_reports.php) pulls all curriculum from `curricula` but doesn't check if `curricula.df IS FALSE` .

**Comment by stickzman** [comment]
What is curricula.df representing?

**Comment by Scott123180** [comment]
df stands for delete flag. If a user selects to delete the curricula, then they don't actually delete it. A superuser needs to delete it for good. But if the delete flag is true, then it won't show that curriculum in the application. In this way, if they delete something by accident, we don't lose any data and a normal user of the application can't see it. 

I don't think the df is pushed to 10.11.12.34 yet, so if you change your code it won't work until the DB is updated.
