### ISSUE TITLE
Error Submitting Form

### ISSUE THREAD

**Issue by BrandonOh** [Capping-CPCA/Web-App#180]
An error occurs when submitting a form, where if you input a street address that doesn't start out with a number such as "house of hope" as someone had on their form it would throw a 22P02 error because it is looking for an integer first. Some of the forms don't have street address and just named shelters so this either needs to have this allow for named buildings or just have it throw an error to tell them to correct it with a street address. This occurs also both on Referral Form and Intake Packet.

Another issue is that if something has not input something correctly such as an e-mail in the referral form it gives a red box error around first and last name telling you that it is missing even though it has something in it already. A red box error is surrounding the e-mail input field but you need to open the form area it is in, it does not open or tell you about the error.

**Comment by sbohner14335** [comment]
We are aware of the address one, Christian is currently fixing this. 

As for the validation bug, I should have fixed that but I believe it is currently in a pull request.

Thanks!
