### ISSUE TITLE
Referral Form Date of Referral Missing Info.

### ISSUE THREAD

**Issue by michelleburd** [Capping-CPCA/Web-App#219]
Viewing or editing a referral form "Date of Referral" is not populated with the data entered.

**Comment by sbohner14335** [comment]
We have it going into the DB, but the field is never actually inserted into a table. The DB team knows about this not sure what a solution is looking like though.

**Comment by michelleburd** [comment]
@CBadame @Dr-Crow Any idea about this?

**Comment by CBadame** [comment]
The `signedDate` in the Forms table should hold the same day that "Date of Referral" would. @Dr-Crow, @jrands, @marcosb1 could we just allow them to pull and update that field?

**Comment by jrands** [comment]
I agree
