### ISSUE TITLE
Addresses for Locations

### ISSUE THREAD

**Issue by algozine** [Capping-CPCA/Web-App#224]
We need to implement the adding and viewing of physical addresses for "Locations" in the UI - I believe this was accounted for in the DB, but the UI doesn't have it yet. I would like to understand what it would take to implement this - since there will be students working on this next semester, perhaps it is something they can do and therefore not something that has to get done in the next few weeks.

**Comment by blackjack26** [comment]
@algozine The newest version of the DB does not have a reference to the addresses table from sites so it has not been implemented. Once it is implemented, it'd take me about 20min to add it to the web app.

**Comment by blackjack26** [comment]
This is the most recent SQL for the `sites` table. It has no connection to addresses
```sql
CREATE TABLE IF NOT EXISTS Sites (
  siteName TEXT NOT NULL,
  siteType PROGRAMTYPE,
  PRIMARY KEY (siteName)
);
```

@CBadame @Dr-Crow

**Comment by CBadame** [comment]
@marcosb1 and I just added the link to the Address table back. The SQL now looks like:
```sql
CREATE TABLE IF NOT EXISTS Sites (
  siteName								TEXT				NOT NULL,
  siteType								PROGRAMTYPE,
  addressID                                                                             INT,
  PRIMARY KEY (siteName),
  FOREIGN KEY (addressID) REFERENCES Addresses(addressID)
);
```
Looks like the field was lost in a merge. You guys should all be set now
