### ISSUE TITLE
Agency Request Participant "Back"

### ISSUE THREAD

**Issue by KCoterwas** [Capping-CPCA/Web-App#26]
After hitting back on the **browser** on the “view intake packet” screen (which is just a 404 right now) hitting the literal “back” button on the participants info page results in a 404 instead of the overall participant results screen
(note: done in chrome)

**Comment by blackjack26** [comment]
This may sound ironic but this is because currently the `404.php` doesn't exist. So you really get two 404s. I've fixed this in my error page's update
