### ISSUE TITLE
Request for Documentation

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Web-App#29]
Was getting set up and took a while and a lot of debugging to see why my pages weren't loading correctly. Please add documentation mentioning that we are using bootstrap 4.x so that nobody else has the same confusion. Thanks! :smile:

**Comment by Scott123180** [comment]
found good pages to include in the documentation:
https://getbootstrap.com/docs/4.0/migration/#panels-thumbnails-and-wells

https://v4-alpha.getbootstrap.com/components

**Comment by blackjack26** [comment]
Thank you Scott! I meant to add that in after talking with the Intake / Referral group. I put it in the wiki <https://github.com/Capping-CPCA/Web-App/wiki/Adding-New-Pages>
