### ISSUE TITLE
Line Wrapping

### ISSUE THREAD

**Issue by KCoterwas** [Capping-CPCA/Web-App#34]
Within Classes, some titles aren't formatted right, allowing for some letters to go onto the next line. 
Ex. Communication/Listening/Criticism/Confrontation/Fair Fighting
Nurturing/Culture/Spirituality

**Comment by blackjack26** [comment]
This is just because `Communication/Listening/Criticism/Confrontation/Fair` is treated as one word. Currently it only breaks at spaces, what would you suggest is an appropriate place to break a word at?

**Comment by KCoterwas** [comment]
Would a space before Criticism and before Culture fix it?
Also, this is probably a database issue, isn't it

**Comment by blackjack26** [comment]
Yes that would fix it. And you are correct, it is how the database stores it, so they would have to update it on their end.

**Comment by k6789j** [comment]
That would fix the current problems but not future times they try to add classes with names like this.  Could we, or the database team if this is more of their problem, add spaces next to / when those are entered?

**Comment by vmjoseph** [comment]
Has this issue been resolved? If not we should alert one of the db team members.

**Comment by michelleburd** [comment]
Again following up on this issue to see if it can be closed. @blackjack26 @CBadame @Dr-Crow @KCoterwas
