### ISSUE TITLE
Implement Version Numbers

### ISSUE THREAD

**Issue by k6789j** [Capping-CPCA/Web-App#37]
Create a system for numbering the versions so that we can label testing and servers

**Comment by k6789j** [comment]
I have set up releases starting with version 0.1  Please create a new release every time a pull request is merged

**Comment by blackjack26** [comment]
If it is a very small release, can I do a third number? Like lets say we were on `0.2` and there was a tiny fix that wasn't even close to a feature being added, could then the new release after the merge be `0.2.1`? Just a thought.
