### ISSUE TITLE
Add Headers to Each File

### ISSUE THREAD

**Issue by KCoterwas** [Capping-CPCA/Web-App#44]
Each file of code should have a commented header of:
Project: PEP Capping 2017 Algozzine's Class
Author:
Description:
Patch Log:

**Comment by blackjack26** [comment]
See <https://github.com/Capping-CPCA/Web-App/wiki/Adding-New-Pages#comment-header>

**Comment by ghost** [comment]
At this moment, the following files don't have headers. I just ran `git grep -L "@author"` on each directory except for `/public` (since there are a lot of imported files), so this might not be the most comprehensive list.
```
/core/view/View.php
/core/view/ViewLoader.php

/views/classes/classes.php
/views/curricula/curricula.php
/views/curricula/curricula_restore.php
/views/dashboard.php
/views/errors/404.php
/views/errors/error.php
/views/locations/locations.php
/views/logout.php

/models/Notification.php
/models/DashboardPanel.php

page_permissions.ini
```

**Comment by blackjack26** [comment]
What i've been doing is just adding the headers as I change the files. Instead of going through each one and making the header. If I change the file in an issue I'll add / update the header. There might be some files that we don't change though so this list is helpful!

**Comment by ghost** [comment]
Yeah I figure a list might be helpful if someone wants to knock some out for some participation points. Although I wouldn't be sure who the original author was.

**Comment by michelleburd** [comment]
I just did another `git grep -L "@author` on develop in the highest-level directory and these are the only files missing headers:

core/view/View.php
core/view/ViewLoader.php
models/DashboardPanel.php
models/Notification.php

@blackjack26 made these so he'll add the headers now and then we can close this issue.
