### ISSUE TITLE
Page Tutorials

### ISSUE THREAD

**Issue by blackjack26** [Capping-CPCA/Web-App#57]
Add tutorials for each page. These tutorials will be displayed when a page is visited for the first time.

In `custom.js` add additional Tutorial objects to the `tutorials` array. Use the function `showTutorial(name)` to show the tutorials on the page.

Page tutorials needed:

- [x] Dashboard
- [x] Participant Results
- [x] Curricula / Classes / Location search
- [x] Reports

Address Issue #66 
Address Issue #74

**Comment by algozine** [comment]
just another clarifying point on my issue #66 >> you should be able to "x" out of any one of the tutorial boxes, not just the first one, and that goes for either when I'm "first" on a page and they come up by default OR when I select "help" and start browsing through the tutorial boxes .. at any point I should be able to "quit" the tutorial and resume working

**Comment by blackjack26** [comment]
Yes, I have a button on each of the tutorials that say "Don't Show" and if you click this button on any of the tutorials it'll prevent all subsequent tutorials from popping up.
