### ISSUE TITLE
Add/Edit Curricula Page Flow

### ISSUE THREAD

**Issue by dtoverington** [Capping-CPCA/Web-App#69]
As I was going through the curricula page to verify database connections were good to go, I ran into an issue with the current flow of adding and editing a curricula. After discussing with Algozzine, we came up with the following suggestions for simplifying the process for the users:

1. When inserting a new curriculum, the page should not give the option to add classes at that stage, only inputting the name, type and max number of missed classes.

2. Once a curriculum is created, the buttons on the curricula cards should be View, Add Class, Change, and Delete. View and Delete will work as they were originally designed but Add Class will only allow them to select and add one class at a time to a curriculum (per Algozzine). Change will be similar to how edit currently works but will remove the ability to add classes from that page (remove will stay on the Change page)

Hopefully this makes sense, if not, Kelly understands the changes and will explain more at your meeting tomorrow.

**Comment by blackjack26** [comment]
Also, a question I've been meaning to ask. When we click the "Create" button after filling out the form, should I have it redirect back to the grid page and show the success instead of showing the success on the form page?

**Comment by kevinmartino1** [comment]
I think it will flow better if it redirected back to the full and updated grid page.  Same thing with the edit function.  Also applies for classes and locations pages.
