### ISSUE TITLE
Print Button UI Integration

### ISSUE THREAD

**Issue by ghost** [Capping-CPCA/Web-App#73]
Multiple pages will need the ability to print, while adding the configuration is easy enough we should probably have a standard for where a print button should appear + look and feel. An idea was in the top bar to the right of the account drop down with the icon only appearing on pages that are "printable". 

Looking for a standard solution any team that needs printing can use.

**Comment by k6789j** [comment]
For look and feel of the button, any print button can use the class 'btn-secondary'.  That will make it grey.

**Comment by sbohner14335** [comment]
Top right print glyphicon?

https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_glyph_print&stacked=h

**Comment by ghost** [comment]
and position it at the top right of the page, or put it on the top-bar ?

**Comment by blackjack26** [comment]
Top right of page. Putting it in the top-bar might make it a little cluttered.

**Comment by stickzman** [comment]
So the glyphicon font set was dropped in bootstrap 4, which is what i believe we are using
