### ISSUE TITLE
Curricula Tutorials

### ISSUE THREAD

**Issue by kevinmartino1** [Capping-CPCA/Web-App#74]
After closing the 2 pop up tutorials within the curricula page, the screen stays grayed out and does not let you click anything.  The user must refresh to get out of this.

**Comment by blackjack26** [comment]
Thanks! I've fixed it in #57. I made it so if the element doesn't appear on the page to skip the tutorial.

**Comment by k6789j** [comment]
That is because no curricula's exist in the database at the moment.  Once there is data it will work
