### ISSUE TITLE
Modify Location View

### ISSUE THREAD

**Issue by vmjoseph** [Capping-CPCA/Web-App#75]
- [x] Location is only: jail, rehab, inhouse

- [x] Curriculum is: fox run, women’s dc, Florence manor etc

- [x] Remove secondary field from location and curriculum

**Comment by k6789j** [comment]
So, I am a little confused about this issue.  When I talked to Algozzine about this, he said that he doesn't want location or curricula limited by our design.  He just wants us to get rid of the type field.  There should be no dropdowns on creating locations and curricula.

**Comment by vmjoseph** [comment]
You are correct- this is just a placeholder to remind us to get rid of the type field. 
See #89

**Comment by k6789j** [comment]
So, just to be clear, they will be able to store anything as a location?  it's not going to be an enum?

**Comment by vmjoseph** [comment]
Location is still a drop-down, as it is a requirement for creating the curricula. 
![create_curricula](https://user-images.githubusercontent.com/9935166/32502335-65f64ae0-c3a8-11e7-9234-a0fc385891fe.PNG)

Location is a enum right now, but we're working on getting that fixed.

**Comment by k6789j** [comment]
No, locations should not be a drop down

**Comment by vmjoseph** [comment]
Could you elaborate as to why not?

**Comment by k6789j** [comment]
So wait, this would be a drop down in the create a curriculum page, and it would be a drop down of whatever they create the locations to be?  Because that might be right.  I might just be confused

**Comment by vmjoseph** [comment]
When we met with Algozzine , we were told to remove locations as a "type" because the client would be confused. This drop down is only for creating a curriculum, as a curricula needs a location.  They are currently unable to create locations due to it being an enum.

**Comment by k6789j** [comment]
But once that is not enum, they will be able to create locations?

**Comment by vmjoseph** [comment]
Yes 😄

**Comment by k6789j** [comment]
Okay, I think we are on the same page...
