### ISSUE TITLE
Ignore case of username

### ISSUE THREAD

**Issue by k6789j** [Capping-CPCA/Web-App#80]
The user should be able to put their username in without worrying about uppercase vs. lowercase letters.  Administrator and administrator should be seen as the same person.  Perhaps, lowercase the whole username before passing it to LDAP.

**Comment by blackjack26** [comment]
The username would have to be defined with lowercase in LDAP and then I could do this. Or an LDAP setting to ignore case needs to be set. More of an LDAP issue

**Comment by k6789j** [comment]
Devin tested today and was able to make three different accounts using the same LDAP credentials, one using Administrator, one with administrator, and one with AdMiNiStRaToR.  LDAP is not username case sensitive

**Comment by blackjack26** [comment]
If you were able to make all those accounts then LDAP is case sensitive. Otherwise you wouldn’t be able to create three accounts that all would be “administrator” in lowercase.

**Comment by blackjack26** [comment]
I understand what you’re saying now. The email being stored should be lowercase.

**Comment by dtoverington** [comment]
For context from the .33 DB...
![image](https://user-images.githubusercontent.com/9370540/32351562-3119be04-bff4-11e7-8d48-c68d4773f8fa.png)

**Comment by k6789j** [comment]
We should not be able to have multiple accounts on our system made with the same ldap credentials

**Comment by blackjack26** [comment]
Yes, we’ll just store it as all lowercase and when it checks for the employee, lowercase the email they typed in.

**Comment by k6789j** [comment]
perfect
