### ISSUE TITLE
Top right account settings

### ISSUE THREAD

**Issue by sbohner14335** [Capping-CPCA/Web-App#81]
Would you consider having the first and last name on the top right pop out the same account settings, help, and log out display as when you click the profile drop down? 

Just a thought!

**Comment by algozine** [comment]
I am not sure what this suggested enhancement is suggesting?  I like the way the upper right drop down works now .. if hovering is supposed to also activate the 'drop down', I suggest that be a 'nice to have' parking lot item for now unless it is a really easy fix or already done... but I don't see it working on 0.5.0 so I am betting it's not??
