### ISSUE TITLE
Magical Modal for Searching Users

### ISSUE THREAD

**Issue by Dr-Crow** [Capping-CPCA/Web-App#90]
@vjoseph2 I heard you had this module that  was used in Scott's attendance section. It allows you to pick the right user after a search? Can you point me in the direction of this/do you have a test server so I can see it? This is important since it will not only be used in attendance but anytime information is being inserted about a participant.  Like for intake packets, referral packets, etc. 
- [x] Pass participant information as parameters in a sql query to find matches
- [x]  Grab all returned results and display in modal
- [x] Allow user to select a matching participant
- [x] Store the selected participant ID for use in referral stored proceedures

**Comment by vmjoseph** [comment]
Hey Jimmy
For Scott's attendance section I pretty much just used an ajax call to query the search results page. It works much like the live search function that can be found on any of our servers (I believe) under "Agency Requests". I'm pasting a snippet of the code used from what I did on Scott's page, but if you'd like to see it in full, its under the "63-view-synced-attendance" branch under "views/attendance/attendance_forms" around line 315.  

Let me know if you need any additional info.

Here's the code associated with the user search:
```javascript
$(document).ready(function(){
		//when uesr clicks the search button within the 'search for person' card
		//open a modal using user input as search query, then display in modal
		$(".active-search").click(function(){
			//grabbing user input
			var participantSearch = $(".search-participants").val();
			//creaing a new form to search the participant result page for user-entered participant
			$('<form class='+'add-participant'+'>', {
				"id": "search-participants",
				"html": '<input type="text" id="searchquery" name="searchquery" value="' + participantSearch + '" />',
				"method": "post",
				//setting the destination url to participant search
				"action": '/participant-search/'+participantSearch
			}).appendTo(document.body);
			//append it to the bottom
			$("body").append("<form class='add-participant' action=''></form>");
			
			//instead of directing the user to a new page, we're going to display the 
			//results of the search in a modal. There is now a modal hidden at the bottom of the screen that will
			//become active once the search is triggered
			$(".modal-body").empty();
			//using ajax to stay on the origin page
				$.ajax({
					type: 'GET',
					url: '/participant-search/'+participantSearch,
					dataType: 'text',
					data: $(".add-participant").serialize(),
					success:function(data){
						//looking for the participant results
						var sentName = $(data).find(".list-group-item");
						//for each result, display a list element with the name of the participant
						//and a 'add to class' button
						$.each(sentName, function(){
							var sentURL = $(this).find('a').attr("href");
							if(sentURL != undefined){
							var sentNameList = $(this).find("span").html();
							console.log(sentURL);
							var matched = sentURL.match( /\/view-participant\/(\d*)/);
							var peopleid = matched[matched.length-1];
							var details = $(this).find(".sublist").text();
							//add the view to the modal
							$(".modal-body").append("<form class=\"add-to-sheet\" method =\"POST\"action=\"\">"+
							"<input type=\"hidden\" value="+peopleid+" name=\"pidLookup\">"+
							"<input type=\"hidden\" value=\"<?=$selected_curr?>\" name=\"curr\">"+
							"<input type=\"hidden\" value=\"<?=$selected_class?>\" name=\"classes\">"+
							"<input type=\"hidden\" value=\"<?=$selected_date?>\" name=\"date-input\">"+
							"<input type=\"hidden\" value=\"<?=$selected_time?>\" name=\"time-input\">"+
							"<input type=\"hidden\" value=\"<?=$selected_site?>\" name=\"site\">"+
							"<input type=\"hidden\" value=\"<?=$selected_lang?>\" name=\"lang\">"+
								"<ul class='list-group'>"+
								"<li class='list-group-item'>"+sentNameList+
								"<input type=\"submit\" name=\"lookupId\" value= \"Add\" class=\"btn cpca float-right submit-search\">"+
								"</li>"+
								"<ul class='list-group'><li class='list-group-item'>"+details+"</li></ul>"+
								"</ul>"+
							"</form>");
							 $("#exampleModal").modal();
							}
							
						})
					}
				});
		});
		
		//allow user to press 'enter' while searching without 
		//resubmitting the whole form just yet
			$('.search-participants').keypress(function(event){
			  if(event.keyCode == 13){
				$('.active-search').click();
				event.preventDefault();
			  }
			});
```

**Comment by Dr-Crow** [comment]
As discussed for this deployment, the only thing you need to do, is query the database for people using the form data: first name, last name, middle initial. If you get a match(s), use the first one and give the peopleID to the store procedure. If you get back no matches, then create a person using the info and give the store procedure the peopleID.  @vmjoseph

**Comment by Dr-Crow** [comment]
@vmjoseph In addition, since the agency referral form can be inserting multiple people: the participant and any agency members associated with them, this process needs to happen multiple times, for the participant and each agency member. 

(do not worry about familymembers and emergency contacts, we're creating new people every time for them)

-john

**Comment by Dr-Crow** [comment]
This should be roughly the query you will be making, do not worry about middle initial. Lets get it to work first. 

Select peopleID from People where firstName = % and lastName = % limit 1
