### ISSUE TITLE
Referral Form Required Fields

### ISSUE THREAD

**Issue by KCoterwas** [Capping-CPCA/Web-App#93]
As of right now, I was able to submit a form with one letter for the first name and one letter for the last name to meet the required fields. Nothing else was required. I'm assuming that a little more information is required to create a unique instance of  a person within the database?

**Comment by blackjack26** [comment]
Nope, actually all that is required for these forms are their first and last name. I believe that is what you've told me @christianmenk @sbohner14335

**Comment by sbohner14335** [comment]
Yes it seems strange, but those are the only two required fields on the form

**Comment by KCoterwas** [comment]
Amazing. Good to know.
