### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by algozine** [Capping-CPCA/Web-App#96]
In the test environment, cached pages is a problem .. as I was on .33 working and things weren't going well, but it was letting me do stuff... As for the client environment, what concerns me is this same thing could happen after we do a redeploy if we aren't clearing cookies / cache for our web app ... or forcing reload or whatever it takes to avoid them running on cached versions of the pages after a new install/upgrade.

**Comment by dtoverington** [comment]
The temporary workaround in Chrome is to go to [chrome://settings/content/cookies](chrome://settings/content/cookies) and delete the cookies associated with the IP address of the server you are trying to access. There may be a better way but this is how I've been doing it.

**Comment by blackjack26** [comment]
We could possibly have a way to check and see if the version changes, and if it has changed, clear the cache through javascript and do a hard reload of the page.

**Comment by algozine** [comment]
Another workaround I had been using is to run in an incognito window

**Comment by vmjoseph** [comment]
Is there anything that needs to be stored in the cookies?

**Comment by vmjoseph** [comment]
Issue is currently solved in branch [96-cookies](https://github.com/Capping-CPCA/Web-App/tree/96-cookies), just needs to be tested.
